config/routes.rb
Demo::Application.routes.draw do
  resources :people
  resources :events do
    resources :attendees, :controller => 'event_attendees'
    resource :location, :controller => 'event_locations'
  end 

  get "welcome/say_hello" => "welcome#say"
  get "welcome" => "welcome#index"
  root :to => "welcome#index"

  

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
	belongs_to :event
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :events
end

app/models/event.rb
class Event < ActiveRecord::Base
	validates_presence_of :name
	has_many :attendees, :dependent => :destroy
	belongs_to :category
	has_one :location
	has_many :event_groupships
	has_many :groups, :through => :event_groupships
	accepts_nested_attributes_for :location, :allow_destroy => true, :reject_if =>  :all_blank
end

app/models/event_groupship.rb
class EventGroupship < ActiveRecord::Base
	belongs_to :event 
	belongs_to :group
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :event_groupships
	has_many :events, :through => :event_groupships
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :event
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
	before_action :find_event

	def index
		@attendees = @event.attendees
	end

	def show
		@attendee = @event.attendees.find(params[:id])
	end

	def new
		@attendee = @event.attendees.build
	end

	def create
		@attendee = @event.attendees.build(attendee_params)
		if @attendee.save
			redirect_to event_attendees_url(@event)
		else
			render :action => :new
		end
	end

	def edit
		@attendee = @event.attendees.find(params[:id])
	end

	def update
		@attendee = @event.attendees.find(params[:id])
		if @attendee.update(attendee_params)
			redirect_to event_attendees_url(@event)
		else
			render :action => :edit
		end
	end

	def destroy
		@attendee = @event.attendees.find(params[:id])
		@attendee.destroy
		redirect_to event_attendees_url(@event)
	end

	protected 

	def find_event
		@event = Event.find(params[:event_id])
	end

	def attendee_params
		params.require(:attendee).permit(:name)
	end

end

app/controllers/event_locations_controller.rb
class EventLocationsController < ApplicationController
	before_action :find_event

	def show
		@location = @event.location
	end

	def new
		@location = @event.build_location
	end

	def create
		@location = @event.build_location(location_params)
		if @location.save
			redirect_to event_location_url(@event)
		else
			render :action => :new
		end
	end

	def edit
		@location = @event.location
	end

	def update
		@location = @event.location
		if @location.update(location_params)
			redirect_to event_location_url(@event)
		else
			render :action => :edit
		end
	end

	def destroy
		@location = @event.location
		@location.destroy
		redirect_to event_location_url(@event)
	end

	protected

	def find_event
		@event = Event.find(params[:event_id])
	end

	def location_params
		params.require(:location).permit(:name)
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController	
	before_action :set_event, :only => [ :show, :edit, :update, :destroy]	

	def index
		@events = Event.all

		respond_to do |format|
			format.html
			format.xml{ render :xml => @events.to_xml}
			format.json{ render :json => @events.to_json}
			format.atom{ @feed_title = "My event list" }
		end
	end

	def new
		@event = Event.new
	end

	def show
		respond_to do |format|
			format.html {@page_title = @event.name}
			format.xml 
			format.json{ render :json => { id: @event.id, name: @event.name}.to_json}
		end
	end

	def create
		@event = Event.new(event_params)
		if @event.save
			flash[:notice] = "event was successfully created"
			redirect_to events_url
		else
			render :action => :new
		end
	end

	def edit
	end

	def update
		if @event.update(event_params)
			flash[:notice] = "event was successfully updated"
			redirect_to event_url(@event)
		else
			render :action => :edit
		end
	end

	def destroy
		@event.destroy
		flash[:alert] = "event was successfully deleted"
		redirect_to events_url
	end
	
	private

	def event_params
		params.require(:event).permit(:name, :description, :category_id, :location_attributes => [:id, :name, :_destroy, :group_ids => []])
	end

	def set_event
		@event = Event.find(params[:id])
	end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :bio, :birthday)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
	def say
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/event_locations_helper.rb
module EventLocationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
	def setup_event(event)
		event.build_location unless event.location 
		event
	end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/event_attendees/edit.html.erb
<%= form_for @attendee, :url => event_attendee_path(@event, @attendee), :html =>{:method => :patch} do |f| %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/event_attendees/index.html.erb
<ul>
<% @attendees.each do |attendee| %>
	<li>
		<%= attendee.name %>
		<%= link_to 'show', event_attendee_path(@event,attendee) %>
		<%= link_to 'edit', edit_event_attendee_path(@event,attendee) %>
		<%= link_to 'destroy', event_attendee_path(@event,attendee),:method =>:delete %>
	</li>
<% end %>
</ul>
<%= link_to 'new attendee', new_event_attendee_path(@event) %>
	

app/views/event_attendees/new.html.erb
<%= form_for @attendee, :url => event_attendees_path(@event) do |f| %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/event_attendees/show.html.erb
<p><%= @attendee.name %></p>

app/views/event_locations/edit.html.erb
<%= form_for @location, :url => event_location_path(@event), :method => :patch do |f| %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/event_locations/new.html.erb
<%= form_for @location, :url => event_location_path(@event) do |f| %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/event_locations/show.html.erb
<h1><%= @event.name %></h1>
<% if @event.location %>
	<p><%= @event.location.name %></p>
	<p><%= link_to "edit", edit_event_location_path(@event) %></p>
	<p><%= link_to "destroy", event_location_path(@event), :method => :delete %></p>
<% else %>
	<p>N/A</p>
	<p><%= link_to "Add location", new_event_location_path(@event) %></p>
<% end %>

app/views/events/_form.html.erb
<%= f.label :name, "Name" %>
<%= f.text_field :name %>
<%= f.label :description, "Description" %>
<%= f.text_area :description %>
<%= f.collection_select(:category_id, Category.all, :id, :name) %>
<%= f.fields_for :location do |location_form| %>
<%= f.collection_check_boxes(:group_ids, Group.all, :id, :name) %>
<p>
<%= location_form.label :name, "Location Name" %>
<%= location_form.text_field :name %>
<% unless location_form.object.new_record? %>
	<%= location_form.label :_destroy, 'Remove:' %>
	<%= location_form.check_box :_destroy %>
<% end %>
</p>
<% end %>

app/views/events/edit.html.erb
<%= form_for setup_event(@event), :url => event_path(@event), :method => :patch do |f| %>
	<%= render :partial => 'form', :locals => { :f => f} %>
	<%= f.submit "Update" %>
<% end %>

app/views/events/index.html.erb
<ul>
<% @events.each do |event| %>
	<li>
		<%= event.name%>
		<%= link_to event.name, event_path(event) %>
		<%= link_to " (XML)", event_path(event, :format => :xml) %>
		<%= link_to " (JSON)", event_path(event, :format => :json) %>
		<%= link_to 'Edit', edit_event_path(event) %>
		<%= link_to "attendees", event_attendees_path(event) %>
		<%= link_to 'location', event_location_path(event) %>
		<%= button_to 'Delete', event_path(event), :method => :delete, :data =>{ :confirm => "Are you sure?" } %>
	</li>
		<% end %>
</ul>

<%= link_to 'New Event', new_event_path %>
<%= link_to 'Atom Feed', events_path(:format => :atom) %>

app/views/events/new.html.erb
<%= form_for setup_event(@event), :url => events_path do |f| %>
<%= render :partial => 'form', :locals => { :f => f} %>
<%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<%= @event.name %>
<%= simple_format(@event.description) %>
<p>Category: <%= @event.category.try(:name) %></p>
<p>Group:
	<% @event.groups.each do |g| %>
		<% g.name %>
	<% end %>
</p>
<p><%= link_to 'Back to index', events_path %></p>

app/views/layouts/_form.html.erb
<%= f.label :name, "Name" %>
<%= f.text_field :name %>
<%= f.label :description, "Description" %>
<%= f.text_area :description %>
<% if @event.errors.any? %>
	<ul>
		<% @evnet.errors.full_messages.each do |mag| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>
<p style="color: red"><%= flash[:alert] %></p>
<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Birthday</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.bio %></td>
        <td><%= person.birthday %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @person.bio %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @person.birthday %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/welcome/index.html.erb
<p>Hola! It's <%=Time.now%></p>
<p><%= link_to 'Hello!', welcome_say_hello_path %></p>

app/views/welcome/say.html.erb
<h1>Hello, World!</h1>
<p><%= link_to "Home", root_path %></p>